### ISSUE TITLE
是否支持i7 CPU的版本?

### ISSUE THREAD

**Issue by g707175425** [badstorm/surface-pro-7-opencore#1]
我的电脑是surface pro7 i7的 请问支持么

**Comment by badstorm** [comment]
I tested only on my Surface that is i5, but I think it should work. But since the graphic is the same, for now graphic acceleration not work.

**Comment by g707175425** [comment]
> I tested only on my Surface that is i5, but I think it should work. But since the graphic is the same, for now graphic acceleration not work.

Thank you very much, i'll try it. Sorry for my poor English.
