### ISSUE TITLE
[Proposal] Workaroud for screen blinking issue

### ISSUE THREAD

**Issue by jackjack1-su** [badstorm/surface-pro-7-opencore#10]
Hey Guys,I've just found a solution of the screen blinking by accident!
Update to the macOS 11.2 Or Downgrade to the macOS 11.0.1(confusing)!
But remember, turn the resolution to the 1368x912 before Up/Downgrade!
(Tested on Surface Pro 7 i5-8GB-128GB Version)

**Comment by jackjack1-su** [comment]
By some test, this is caused by some NVRAM Problems On SP7. But it's not clear at all.(I'm looking for these problems)

**Comment by Ehco1996** [comment]
@jackjack1-su  you mean if i upgrade my system to macOS 11.2 and screen resolution to the 1368x912 can slove the screen binking?

it's like magic

**Comment by Xiashangning** [comment]
@jackjack1-su So you are now using SP7 with hidpi enabled in macOS 11.2? Could you please upload your nvram content as well as your EFI folder for comparison?

**Comment by jackjack1-su** [comment]
emmm.. I've cleaned the nvram...(To test the WEG Features)
And seems the ACDT is solving some WEG bugs on Ice Lake platform(Such as EL[0] NULL Problem);
So I recommend to stay on other resolutions and wait for the new version of WEG.
Closed(Because it's not widely reproducible)
Will reopen when found solution(s)

**Comment by Xiashangning** [comment]
No, in fact I reinstalled macOS 11.0.1 and then upgraded it to macOS 11.2.1.
After the installation completed, for no reason, the screen stops blinking....
So your method does work, thanks for your comment XD

**Comment by jackjack1-su** [comment]
It works?
However, don't clean your nvram.If you cleaned your nvram, it seems blinking again.
@badstorm maybe you can put it to the README?

**Comment by Xiashangning** [comment]
Sadly, after serval reboots, it starts to blink again...

**Comment by badstorm** [comment]
@jackjack1-su I had found the same workaround with the last OS update. In my case it was sufficent cheange resolution after the update (I had also updated the readme file). But after some reboots the screen blinking again and i need to set non retina resolution.

Are you sure that your surface never blinking again?

**Comment by jackjack1-su** [comment]
hey guys, I believe I've found the real solution.
Use the plist here[](https://github.com/khronokernel/DarwinDumped/blob/master/MacBookAir/MacBookAir9%2C1(2)/Device%20Properties/device-properties.plist)
Copy the new items and change the ig-platform-id.
Tested on my surface.

**Comment by jackjack1-su** [comment]
Thx _**m0d16l14n1**_

**Comment by Xiashangning** [comment]
@jackjack1-su I saw you have posted a comment just a few hours ago, what happened, why you deleted your comment? How does that solution works on your SP7?

**Comment by jackjack1-su** [comment]
> @jackjack1-su I saw you have posted a comment just a few hours ago, what happened, why you deleted your comment? How does that solution works on your SP7?

I've found a solution, but the cursor is broken.

**Comment by jackjack1-su** [comment]
And I don't know how to let the cursor return to normal.

**Comment by jackjack1-su** [comment]
The solution is here: [https://github.com/khronokernel/DarwinDumped/blob/master/MacBookAir/MacBookAir9%2C1(2)/Device%20Properties/device-properties.plist](url)
Add the new items and overwrite the ig-platform-id.

**Comment by Xiashangning** [comment]
Have you tried patching the frame buffer? like altering fbmem and stolenmem. Since SP7 only has 60MB dvmt preallocated...

**Comment by Xiashangning** [comment]
And which items do you add?

**Comment by jackjack1-su** [comment]
just add the new items and ovetwrite the ig-platform-id.

**Comment by jackjack1-su** [comment]
my config now is here.

[config.plist.zip](https://github.com/badstorm/surface-pro-7-opencore/files/6094436/config.plist.zip)
Use my Device Properties and remove all the boot-args.

**Comment by jackjack1-su** [comment]
(For the sound card, you can easily use the newest AppleALC release and inject the id 35.

**Comment by jackjack1-su** [comment]
And it works after several reboots and "sudo nvram -c".
I believe it's the final solution.

**Comment by jackjack1-su** [comment]
Closed.

**Comment by Xiashangning** [comment]
Hello, thank you for you hidpi patch. I have tested and indeed it does work pretty fine. I don't know how many items have you added, but for me only three are needed.
1. `AAPL,GfxYTile` = 01000000 
2. `GraphicsBacklightSetup-0` = 00000100 00000000 AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA 00000000 00000000 00000000 00000000 
3. `GraphicsDisplaySetup` = 00000100 00000000 04000000 8C0A0000 01000000 00000100 00000300 0000906C 8A0F0000 0000000A 00004006 00005000 00000000 00000000 00002E00 00000000 00000000 00000800 00002000 00000120 00000008 00000000 00010001 00000000 00010000 00040000 00000000 01010000 00000000 00000040 0B000008 07000000 2D000001 00000000 00000000

**Comment by Xiashangning** [comment]
And my frame buffer id is 8a5a0000

**Comment by badstorm** [comment]
I have update the config to the last release following your suggestion. Now works but only when i'm logged in. In the login screen my screen continue blinking. Do you have the same problem?

**Comment by jackjack1-su** [comment]
> I have update the config to the last release following your suggestion. Now works but only when i'm logged in. In the login screen my screen continue blinking. Do you have the same problem?

Yep. However, I don't mind.
