### ISSUE TITLE
Surface Pro 7 Ventura no touchscreen

### ISSUE THREAD

**Issue by sonvirgo** [badstorm/surface-pro-7-opencore#105]
[dsdt.aml.zip](https://github.com/badstorm/surface-pro-7-opencore/files/10950639/dsdt.aml.zip)
![Screen Shot 2023-03-12 at 1 32 10 PM](https://user-images.githubusercontent.com/10823037/224540531-512641bf-e063-4274-bac3-a2642db4e90d.png)
[Uploading ioreg.zip…]()

**Comment by zxx457** [comment]
I have the touchscreen to worked fine in Ventura,But I forget how ...  But I can share you the EFI. 

But the bluetooth , sometimes breaks, no idea what  happened. 

https://1drv.ms/u/s!Au1iV4yNYuuM2xtzf8QMFo7gnopP?e=0WbyIb

**Comment by sonvirgo** [comment]
> I have the touchscreen to worked fine in Ventura,But I forget how ... But I can share you the EFI.
> 
> But the bluetooth , sometimes breaks, no idea what happened.
> 
> https://1drv.ms/u/s!Au1iV4yNYuuM2xtzf8QMFo7gnopP?e=0WbyIb

@zxx457 Thank you very much, I will try your EFI asap.
