### ISSUE TITLE
About this Mac - wrong processor reported

### ISSUE THREAD

**Issue by adrianplambert** [badstorm/surface-pro-7-opencore#107]
I have the SP7 1065G7 Quad Core i7 but the About This Mac report thinks it's a 1.5Ghz Quad Core i5. Is this just superficial or will it limit the processing power based on what it believes is in the laptop?

**Comment by xealstorm** [comment]
Both CPUs (i5 and i7) fall back to the i5 CPU in the Apple universe. So the i7 version will show the i5. However it doesn't affect the CPU. For example, if you launch Cinebench or Geekbench, they will report correct CPU (i7 in your case).
