### ISSUE TITLE
I have a problem about the UEFI

### ISSUE THREAD

**Issue by 24532** [badstorm/surface-pro-7-opencore#11]
if you have applied the recent Microsoft Surface Firmware Update(on Jan 7th), then the system will block you completely from booting Opencore

**Comment by jackjack1-su** [comment]
it may be fixed in 0.6.6 (you can download it at gitee.com/shuiyunxc/Opencore   And the pwd is 544133143 for the zip file)

**Comment by jackjack1-su** [comment]
Check the Differences.pdf for quirks setting

**Comment by badstorm** [comment]
https://github.com/badstorm/surface-pro-7-opencore/issues/9
