### ISSUE TITLE
Can't use Type Cover touchpad/keyboard

### ISSUE THREAD

**Issue by LordImmaculate** [badstorm/surface-pro-7-opencore#119]
I can't use the Type Cover's touchpad and keyboard. I didn't change anything in EFI Folder. Using MacOS Montrey downloaded via OpenCore's macrecovery.

**Comment by reddit-reaper** [comment]
make sure your kexts are in  the correct order. its working properly for me on ventura when i updated everything

**Comment by LordImmaculate** [comment]
Okay, thanks
