### ISSUE TITLE
[Proposal] AppleALC Support

### ISSUE THREAD

**Issue by jackjack1-su** [badstorm/surface-pro-7-opencore#12]
AppleALC Customize done yesterday
haven't merge to the acidanthera,but self compile kext is tested.
layout-id:35
Known issue: Electric current sound while 3.5mm is plugged in

File will be uploaded as soon as I arrive home

**Comment by jackjack1-su** [comment]
[Uploading AppleALC.kext.zip…]()

**Comment by jackjack1-su** [comment]
[AppleALC.kext.zip](https://github.com/badstorm/surface-pro-7-opencore/files/5918224/AppleALC.kext.zip)

**Comment by badstorm** [comment]
@jackjack1-su if you want to help improving this configuration you are very welcome, but please use PR instead open an issued with file attached. :) Thanks

**Comment by jackjack1-su** [comment]
alright，i'll open a PR when I get home
Sorry about that:)

**Comment by jackjack1-su** [comment]
has merged to the newest AppleALC release.
Closed.
