### ISSUE TITLE
Bootloop when upgrading to Sonoma. 

### ISSUE THREAD

**Issue by Eatham532** [badstorm/surface-pro-7-opencore#120]
I am guessing this is due to the Surface Pro 7's GPU being incompatible. [Read more here](https://gist.github.com/brian105/25cdec317da858359fd74f52f4ac4308).

I understand that you don't have access to a Pro 7 anymore. If I have time, I will see if I can make a fix for you.

**Comment by blitzdose** [comment]
I can't belive I got this to work by myself. MacOS Sonoma working on my Surface Pro 7 (I had the same bootloop Issue).
Here are the steps you need to do:
- Update WhateverGreen to the newest version: https://github.com/acidanthera/Lilu/releases
- Upgrade Lilu to the newest version: https://github.com/acidanthera/Lilu/releases
- Set "AAPL,ig-platform-id" to 0x8A520000 (You have to put in the value byte-reversed: **0000528A**)
  - You will find that option under DeviceProperties, this value is for the **Iris Plus G4** iGPU of my Surface, I don't know if there are multiple GPUs inside the Surfaces

Thats it. Just boot it up and your Surface is running MacOS Sonoma

<img width="1368" alt="Bildschirmfoto 2023-12-04 um 20 06 39" src="https://github.com/badstorm/surface-pro-7-opencore/assets/35041688/f0cfe187-00a2-47e5-83c0-b312346990b1">

**Comment by Eatham532** [comment]
Can confirm it works. I will make a pull request to make these changes
