### ISSUE TITLE
[Question] How update VoodooI2C and VoodooHID?

### ISSUE THREAD

**Issue by Xiashangning** [badstorm/surface-pro-7-opencore#15]
Hi, I have tried to upgrade the kext to the latest version before and have found that I could not upgrade VoodooI2C, so I kept it as it is from your project. I thought it was 2.4.2 from the official site. But recently I found that even if I replace my VoodooI2C with the official release of the version 2.4.2. I cannot use my typecover keyboard, only the trackpad. So I am wondering if you have made some custom changes to the official 2.4.2 version.
If so, can you tell me what changes? I want to apply it to the latest version.
Thanks

**Comment by jackjack1-su** [comment]
In fact, you can download the 2.4.4 version from the [https://github.com/bigsadan/surface-pro-4-hackintosh](url).
It's true that there are some custom changes.(However, I don't have the code)

**Comment by Xiashangning** [comment]
Sadly, using his version(neither 2.4.4 nor 2.5.2) causes kernel panic after waking up from sleep, reporting `unable to change the collection` (OSCollection) thing. I believe that can be easily fixed as long as we get the source code... I have posted an issue in his repo hoping to get permitted to the source code.

**Comment by badstorm** [comment]
@Xiashangning please share here the link of the issue you posted so we can keep track.

**Comment by Helloearther** [comment]
麻烦楼上几位老兄用中文问和答，省得和你们一样的中国人看着费劲，谢谢。。。哈哈哈哈。

**Comment by badstorm** [comment]
I close it for inactivity
