### ISSUE TITLE
Informations for fixing the UEFI update issue (v 9.102.140.0)

### ISSUE THREAD

**Issue by sauregurke** [badstorm/surface-pro-7-opencore#16]
(This also has a few helpful tips on things I have gotten working on my SP7)

**SetupVirtualMap enabled** was the crucial quirk that got my surface up and running **with the latest 9.101.140.0** (now 9.102.140.0) UEFI update. **You must upgrade to open core 0.6.6 or 0.6.7 for this to work** (I am on 0.6.7; this worked fine in the past on both 0.6.6 and 0.6.7 and both release and debug builds, which is to be expected). _If upgrading OpenCore and this quirk don't work together, try just using the quirk settings I have in the attached config file._ You could paste in your smbios, I suppose, but you also don't necessarily have the files I have, so just make sure.

The only file of badstorm I used is their config file, which I modified quite a bit to work for me - I do heavily recommend that you do the same, and use a fresh copy of opencore for the rest. 

It is stripped of a few irrelevant items for my privacy, of course. In my experience, AppleALC layout 35 worked pretty well, but there was static coming from the speakers with headphones plugged in and it kernel panicked when I plugged in my monitor (display audio maybe?) so I switched back to voodooHDA. On mine, though I have not done a whole lot of investigative work on the subject, Itlwm is the only one that works - Airportitlwm did not connect to any networks, and airdrop didn't work anyways.

**These quirks are really the only things you should be taking note of in my file. My framebuffer patches didn't end up working, as I explain later.** I have a few people on the Hackintosh discord trying to work out a battery DSDT patch but so far it seems as if there will need to be an entire separate kext made for it to work. The Surface-Linux team apparently has already made the stuff to do it (I am no expert in this, so take my version with a grain of salt) but it still has to be made. The reason being it's part of a weird "surface integration" layout that makes you wonder if Microsoft is just doing these things to make people mad. 

**Please let me know if you get a battery patch working.** Indeed, the trackpad works fine with those commands without the "sudo" part (not sure why - literally makes no sense to me), though I believe macOS treats power management carelessly without a battery present. I will update here if we get a battery patch working. _Even if your patch only gets the battery to report at 100% as I saw in a SP6 Hackintosh build, that would still be insanely useful. Please do share!_

I did get iservices working using my MAC address (without colons) as the ROM and a MacBookAir9,1 smbios. Chances are you will need a long-standing account for iservices to work; see the opencore post install guide for more info.

Through many hours of trial and error, I also cannot get 4K to work smoothly all the time with either the -cdfon boot flag on Catalina OR enable-max-pixel-clock-override in DeviceProperties on Big Sur. Please let me know if you find a configuration that reliably works; I couldn't possibly list all of the device-ids, frame buffer patches, or other things I have tried. HOWEVER with the settings in the attached config file, you may be able to boot with an external (1080p works for me) monitor connected. Not sure what it does to the software, but sometimes it will cause 4K60 to work perfectly.
[config.plist.zip](https://github.com/badstorm/surface-pro-7-opencore/files/6104948/config.plist.zip)

**Comment by sauregurke** [comment]
So in a nutshell. you can indeed get opencore to work on the latest UEFI update. If need be, I can share more of my EFI folder. I can understand paranoia in that it might not work for certain people, so perhaps just add this as a note?

**Comment by Xiashangning** [comment]
Hi, I have a few comments on your config.plist
- AppleALC KP when attaching external monitor: try using No-hda-gfx = 'onboard-1' for the audio card in `DeviceProperties` section.
- Battery DSDT: It is impossible that just a SSDT patch would make the Surface series's Battery work. Because Surface uses a custom UART module called Surface Serial Hub to mange all the request sending from _SAN.RQST(You can see that call in _SAN.BST) and windows & linux both uses that to get all the information like battery, performance, adapter status etc. I am trying to port the code from Linux-surface but so far it seems to hard to do so.(Maybe more manpower is needed)
- As for the fake battery status, here I have made one of my own. You can just use that along with SMCBatteryManager, do note that it is completely a fake one and always shows 100% without AC plugged in(This is done intentionally for power management).
[SSDT-Fake-Surface-Battery.aml.zip](https://github.com/badstorm/surface-pro-7-opencore/files/6134003/SSDT-Fake-Surface-Battery.aml.zip)
- The hidpi issue: see another issue thread in this repo. I have added some mba9,1's device properties and now in most cases, you can boot with hidpi enabled, no screen glitching at all.

**Comment by jackjack1-su** [comment]
About the fake battery, it should just be used in installation progress.
While the ssdt is loaded, the settings of the touchpad are unlocked. 
After configuration, the ssdt should be deleted.(Because the speaker problem)

**Comment by jackjack1-su** [comment]
Hmmm
The Airportitlwm works well for me, and the continuing works well.(Except Airdrop and hotspot)

**Comment by sauregurke** [comment]
That’s awesome! You and the helpful folks on the hackintosh discord arrived to the same conclusions about battery patching (how it needs a special UART module patch) and considerations of porting over from windows-linux. Not sure how I can help a whole lot as I am still a noob in programming but I’ll definitely be taking a closer look as soon as I get caught up in my work. The issues with audio and the fake battery patch make sense, as the discord folks also were able to make one (albiet, it only seemed to work with ACPIBatteryManager instead of SMCBatteryManager, which sort of makes sense to me). The only thing is that macOS seems to run a bit more efficiently when it sees a battery, but that could just be me. I’ll be sure to try out your high DPI fix and report back here.

Thank you so much for the work you have done for the hackintosh community!

**Comment by sauregurke** [comment]
Just with simple copy-paste-reboot of your high DPI fix, I seem to be having the same issue. I am trying to diagnose and rebooting a few times as you said.

**Comment by jackjack1-su** [comment]
Maybe a simple nvram reset?

> Just with simple copy-paste-reboot of your high DPI fix, I seem to be having the same issue. I am trying to diagnose and rebooting a few times as you said.

**Comment by sauregurke** [comment]
That seems to have fixed it! Thank you!

I noticed that you have quite a few hot patches. Did you patch these yourself?

**Comment by jackjack1-su** [comment]
> That seems to have fixed it! Thank you!
> 
> I noticed that you have quite a few hot patches. Did you patch these yourself?

Such as rps-control and enable-dvmt-calc-fix?

**Comment by jackjack1-su** [comment]
I've use the DeviceProperties instead of the boot-args.

**Comment by jackjack1-su** [comment]
I add these patches and deleted all the boot-args.

**Comment by sauregurke** [comment]
Ah. My apologies, I was referring to the MCHC and PPMC as from my brief research, I thought they were hot patches. I apologize; I’m still a novice in this :P

**Comment by jackjack1-su** [comment]
Nevermind. ：）

**Comment by sauregurke** [comment]
Do you think the audio issues (with AppleALC) would be fixed with such a UART patch? Furthermore, is there any power management benefit to having macOS see a battery?

It is worth mentioning that the static noise that comes with AppleALC + fake battery patch does not happen with VoodooHDA. However, using the microphones with VoodooHDA is unbearable, so AppleALC would be ideal.

**Comment by badstorm** [comment]
Since I updated to OC 0.6.7 I can close this issue. Feel free to continuing chat here if you need. :)

**Comment by Xiashangning** [comment]
@sauregurke Hey, you said about some folks who try to port the source code from linux. I am thinking that maybe we can create a repo in GitHub, so that we can develop the kext together.
You know, more men more power. The code from linux is not large, we can easily delete those Surface Laptop and Surface Book things. Only keep SSH and SAM sort of stuff. I know few about UART specs so definitely we need a expert in this domain.

**Comment by sauregurke** [comment]
For sure! I can link it in the discord in case the others would like to contribute, as well, if that works for you.

**Comment by sauregurke** [comment]
Are you still down to open that repo? I’ve been learning as much as I can about ACPI patching.

**Comment by Xiashangning** [comment]
Of course I will, still need some time to grab what I have done so far. However, as I have said before, we need some expert in UART drivers, at least in Linux Kernel development. Don't count on me, I know very few on macOS kernel nor Linux kernel.
BTW, maybe you can ask around in your discord to see if some one is interested in this project and have a decent knowledge in this domain.
As soon as I finished cleaning up my work, I will open a repo.

**Comment by sauregurke** [comment]
Hey, I’m still interested in working on this port if you are. Please let me know!

**Comment by Xiashangning** [comment]
@sauregurke see my repo please, https://github.com/Xiashangning/BigSurface. More work is needed to be done.

**Comment by sauregurke** [comment]
Awesome! Thank you so much! I will take the next few days to poke around and try to make sense of it (and maybe even start working!). I’ve already put the repo in the discord, so hopefully others can chip in.

**Comment by sauregurke** [comment]
@Xiashangning does sleep work for you, as in does the CPU turn off during sleep? I have been trying to fix this issue for weeks, and I am wondering if it has to do with the UART module we are working on. My CPU constantly idles at around 0.6% (non-Unix) utilization during sleep, which causes about 70% battery drain after 12 hours of sleep.

**Comment by jackjack1-su** [comment]
> @Xiashangning does sleep work for you, as in does the CPU turn off during sleep? I have been trying to fix this issue for weeks, and I am wondering if it has to do with the UART module we are working on. My CPU constantly idles at around 0.6% (non-Unix) utilization during sleep, which causes about 70% battery drain after 12 hours of sleep.

Check the hibernate settings?
Hibernate mode 25 and Auto in config
It works for me (Computer "shutdowns" after sleep)

**Comment by sauregurke** [comment]
Does this turn off the CPU during sleep? My problem is the CPU never turns off during sleep, which uses lots of power. On my other hackintoshes/macs, iStat Menus does not log any system activity because the CPU is turned off.

I am trying your fix now; I ask because I do not see this fix in my working hackintosh which sleeps correctly (the CPU turns off).

**Comment by AIP21** [comment]
> Does this turn off the CPU during sleep? My problem is the CPU never turns off during sleep, which uses lots of power. On my other hackintoshes/macs, iStat Menus does not log any system activity because the CPU is turned off.
> 
> I am trying your fix now; I ask because I do not see this fix in my working hackintosh which sleeps correctly (the CPU turns off).
> 
> —————————- Another interesting detail: pmset -g log reports “Total Sleeps/Wakes since boot at (date and tame) : 0” so this is another indicator my device is not sleeping. No kernel assertions and really no pointers. I noticed that our surfaces don’t seem to have a standard SMBus.

When I run "pmset -g log" it reports the same thing. That same command also says that IODisplayWrangler is preventing sleep. Is there a fix to this yet? My surface is slightly warm and the battery drains when "sleeping" so I doubt it actually is asleep.
