### ISSUE TITLE
How fast ap7 on Big Sur?

### ISSUE THREAD

**Issue by omarhaya** [badstorm/surface-pro-7-opencore#17]
Hi, I want to buy sp7 to hackintosh so can any one please tell how fast it runs on Big Sur ? Or any geekbenchmark results some one can share ?or does it lag or overheated under tasks like browsing or doing simple tasks ? I will be so glad to hear from any one tested it

**Comment by jackjack1-su** [comment]
Nope. It never overheats and all the things works well except the camera and the battery display.The resolution is fixed on my one.
However, your issue is invalid. These questions should be asked in the store or other forums. Plz close it.
