### ISSUE TITLE
Unable to start the MacOS installer

### ISSUE THREAD

**Issue by edmondt** [badstorm/surface-pro-7-opencore#18]
Tried release Release 1662, 1664, 1665, 1667. 

Install OS X Option does not appear; 
- Plugged in external USB with Big Sur (installed)
- External Big Sur will show, but failed to boot

This is on a Surface Pro 7, i5 8GB 128GB

**Comment by alexfcab** [comment]
I'm in the same situation! Opencore boots and can interact with the picker but there's no install option

**Comment by jackjack1-su** [comment]
Aren't there any log or error message?
We can't help without those informations.

**Comment by jackjack1-su** [comment]
However, I don't have any problem on installing or booting.
All problems are fixed in the OC 0.6.7.

**Comment by badstorm** [comment]
> I'm in the same situation! Opencore boots and can interact with the picker but there's no install option

If you don't see the USB Key (the installer) in most case is a issue with the HFS driver. You can try to use different drivers replacing the actual `OpenHfsPlus.efi` with another one (for example [HfsPlus.efi](https://github.com/acidanthera/OcBinaryData/blob/master/Drivers/HfsPlus.efi)) 

For boot issue, try to use OpenCore "debug" version and update the "Debug" section under Misc in config.plist. So you can get more info and understand what's going on.

**Comment by Muppet1313** [comment]
Same issue here. I have system UEFI firmware 9.102.140

**Comment by badstorm** [comment]
Have you tries what suggest here https://github.com/badstorm/surface-pro-7-opencore/issues/20 ?

**Comment by jackjack1-su** [comment]
Use the debug version and use the verbose mode to boot.(-v in boot-arg)
This will bring us many useful logs.

**Comment by jackjack1-su** [comment]
Post the log picture here plz.

**Comment by badstorm** [comment]
I close it for inactivity
