### ISSUE TITLE
Power management support missing

### ISSUE THREAD

**Issue by g707175425** [badstorm/surface-pro-7-opencore#2]

**Comment by badstorm** [comment]
What do you mean exactly?

**Comment by g707175425** [comment]
I'm talking about whether the electricity can be displayed, sorry for my poor English. 😅

**Comment by badstorm** [comment]
I think it is enough to add _SMCBatteryManager_. 
I'll do it in the next update. ;)

**Comment by mdrawdy95** [comment]
> I think it is enough to add _SMCBatteryManager_.
> I'll do it in the next update. ;)

Thanks your info helped me get my sp7 working except for the battery but I see you will add it. Thanks

**Comment by badstorm** [comment]
I tried to add a _SMCBatteryManager_ but no battery status. I'll try to investigate in the next releases.

**Comment by g707175425** [comment]
> I tried to add a _SMCBatteryManager_ but no battery status. I'll try to investigate in the next releases.

thx, look forward to your good news 😄

**Comment by g707175425** [comment]
> I tried to add a _SMCBatteryManager_ but no battery status. I'll try to investigate in the next releases.

Here is a project which has driven the Bluetooth.

[https://github.com/ati46/surfacepro7-oc](url)

**Comment by badstorm** [comment]
Thanks @g707175425 for your suggestion. I make some updates, but the battery still doesn't work. 
I will continue to look for a solution.

**Comment by g707175425** [comment]
> Thanks @g707175425 for your suggestion. I make some updates, but the battery still doesn't work.
> I will continue to look for a solution.
😄

**Comment by hackintosher121** [comment]
I reckon you might need to patch the DSDT using Rehabman's guide on tonymacx website. I haven't ry it but I might try it later.

**Comment by badstorm** [comment]
I have already tried to create the patch, but unfortunately the Rehabman documentation doesn't seem to fit with the Surface Pro 7's DSDT.

Feel free to test yourself and let me know if you discover anything new.

**Comment by hackintosher121** [comment]
> I have already tried to create the patch, but unfortunately the Rehabman documentation doesn't seem to fit with the Surface Pro 7's DSDT.
> 
> Feel free to test yourself and let me know if you discover anything new.

Have u tried to use the surface pro 4 DSDT patch? I don't really have time to test it recently due to school work, so can u try it for me?

**Comment by badstorm** [comment]
@hackintosher121 I tried but it doesn't work. I think the SFP7 DSDT is too different.

**Comment by hackintosher121** [comment]
Prob then, btw thx 4 testing it out 4 me

**Comment by omarhaya** [comment]
Hi guys does the cpu works on its full power ? Any one tried geekbenchmark for testing ?

**Comment by jackjack1-su** [comment]
> Hi guys does the cpu works on its full power ? Any one tried geekbenchmark for testing ?

In my own, it works well.

**Comment by badstorm** [comment]
I close it for inactivity
