### ISSUE TITLE
Cannot boot MacOS Catalina or Big Sur

### ISSUE THREAD

**Issue by Panja0** [badstorm/surface-pro-7-opencore#20]
I followed the guide from https://dortania.github.io/OpenCore-Install-Guide
Downloaded Catalina and created an USB drive with Rufus.
Copied the EFI directory from here, created a folder called `com.apple.recovery.boot` and copied the BaseSystem.chunklist & BaseSystem.dmg files in that folder. Both folders (EFI + com.apple.recovery.boot) are in the root of the usb thumb stick.

I'm getting the OpenCore Boot Menu (REL-067-2021-03-01).
1. USB external
2. Reset NVRAM

Both options don't seem to do much. I cannot boot in to OSX.

Surface Pro 7, i5, 8GB ram, 256GB ssd. Secure boot has been disabled.

Any idea?

**Comment by badstorm** [comment]
For Catalina you need to use Release [1559](https://github.com/badstorm/surface-pro-7-opencore/releases/tag/1559)

**Comment by Panja0** [comment]
Thanks for the quick reply. 
The newer versions of OC are not compatible with Catalina? 

For which OS are they?

**Comment by Panja0** [comment]
Just tried the same [OpenCore release](https://github.com/badstorm/surface-pro-7-opencore/releases/tag/1667) but now with the latest MacOS, Big Sur. Same problem...

Getting the 2 options while booting but it does not load the installer.

**Comment by Panja0** [comment]
I just tried the suggested settings from [https://github.com/badstorm/surface-pro-7-opencore/issues/21#issuecomment-806078959](here.)

I now get the Apple log but it does not go any further than that.

**Comment by Panja0** [comment]
Using a (real) Mac to create a Big Sur usb installer (full install) and using the 2 settings provided in the other issue thread got me a little further. I can get beyond the Apple logo but as soon as the installer start (or at least I think it starts) I'm getting images that I need to enable a button on a Magic Mouse and MacBook.

**Comment by Panja0** [comment]
Finally got it to work! Using the full installer and little bit of patience.
