### ISSUE TITLE
cant boot into MacOS installer

### ISSUE THREAD

**Issue by lennykeks** [badstorm/surface-pro-7-opencore#21]
I'm on Surface pro 7 i5 8Gb ram and 128Gb

I tried to boot from the OpenCore boot stick. Got the EFI folder from repository and macos BigSur directly with the OC installation. So I got both folders "com.apple.recovery.boot" and "EFI" on my USB. 

Now when I boot up the SurfacePro and disable Secure-boot and take the USB as boot device, I only get "Windows" as a boot option. I'm on OC REL-067-2021-03-01

Already tried other MacOS version

How do I get the install MacOS option in the OC menu?

Thanks

**Comment by mkarer** [comment]
This worked for me (with the full installer):

Enable SetupVirtualMap
Enable DisableSecurityPolicy

**Comment by lennykeks** [comment]
Sorry how do I do that actually?

**Comment by lennykeks** [comment]
ok I got it :)

changed both to true but nothing changed, now I only see the windows boot option in some nice Picture... 

Any other ideas?

**Comment by badstorm** [comment]
Duplicate https://github.com/badstorm/surface-pro-7-opencore/issues/18
