### ISSUE TITLE
Trackpad not recognized correctly

### ISSUE THREAD

**Issue by Panja0** [badstorm/surface-pro-7-opencore#23]
On the frontpage it says:

> // This configuration works for me, but someone make it work removing sudo
> 
> sudo defaults write NSGlobalDomain com.apple.trackpad.forceClick -bool false
> sudo defaults write com.apple.AppleMultitouchTrackpad ForceSuppressed -bool true
> sudo defaults write com.apple.AppleMultitouchTrackpad ActuateDetents -bool false
> 
> sudo defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true 
> sudo defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true 
> sudo defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1 
> sudo defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
> 
> sudo defaults write com.apple.AppleMultitouchTrackpad Dragging -bool true 
> sudo defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Dragging -bool true
> 
> # REBOOT

I've tried that but still I'm getting the "Bluetooth Mouse or Trackpad setup" popup everytime I reboot.
And also it pop ups every once and a while. Annoying AF... ;-)

Any way to fix that?

Surface Pro 7:
i5 / 8GB / 256GB
MacOS 11.2.3

**Comment by badstorm** [comment]
Have you try this?

`// This configuration works for me, but someone make it work removing sudo`

**Comment by Panja0** [comment]
Sorry I had to add to my post that I tried using all command with and without sudo.

**Comment by jackjack1-su** [comment]
Check the issue #16 in this repo.
Add the Fake Battery SSDT and you can see the perf working.
Remove the SSDT after the work done.
Sorry about no link.(I'm using phone to reply)

**Comment by Panja0** [comment]
I added the "SSDT-Fake-Surface-Battery.aml" file to the ACPI folder but it does not make a difference.
Strange thing is that the screen flickering is also back. Using the latest 1667 build but the flickering comes and goes.

**Comment by jackjack1-su** [comment]
So your computer hasn't regonize the touchpad.Use the @Xiashangning 's version of VDI2C.(You may find it in his/her repo.)

**Comment by Panja0** [comment]
@jackjack1-su 
Thanks for the reply! I tried the kexts from Xiashangning's repo but still no joy.
For some reason my typecover has giving some problems. From time to time the trackpad does not work at all and I have to detach the typecover from the Surface and re-attach for it to work.

**Comment by jackjack1-su** [comment]
So i think it's your hardware problem(Because it works well for me)
