### ISSUE TITLE
Stuck at Apple Logo after installation 

### ISSUE THREAD

**Issue by lennykeks** [badstorm/surface-pro-7-opencore#24]
Hi,

still trying to install BigSur on my surface pro7 i5 8Gb RAM 128Gb. 

Created a real Install Stick on my Mac Book pro, booted with Open core and changed something kn my confit.plist

„Enable SetupVirtualMap“
„Enable DisableScirityPolicy“
—> Withouth these changes I couldn’t see the macOs install stick 

on my Surface pro and got into the installer… I normally started the installation process. After  14min the surface restarted and I booted from the internal drive. now I only see the Apple logo and the surface keeps restarting after a few seconds… Went into verbose and got this…
![83FA41FC-53F1-4FC5-82B4-5826265EA7A5](https://user-images.githubusercontent.com/26120005/112722790-c0621e00-8f0b-11eb-9708-d0c1d35bd94e.png)

Anyone could help? 

Thanks

**Comment by jackjack1-su** [comment]
Reinstall it and try Again.

**Comment by lennykeks** [comment]
Already did, no change :(

**Comment by jackjack1-su** [comment]
It reboots when the 2nd phase starts.
Clean NVRAM and try again?(By the Cleannvram.efi in the "tools" directory)
Or you can try the "Recovery" type of system?(It's famous in China)(You can easily find it on Baidu or other else)
Sorry about no real solution.(I haven't met that problem before and I can't find any problems except for the suddenly [EB|Reboot])

**Comment by jackjack1-su** [comment]
I'll be not able to reply for at lease 5 days because of my study.
Sorry.

**Comment by lennykeks** [comment]
Ok gonna try this stuff later…

**Comment by lennykeks** [comment]
Hi again, maybe anyone got a solution for my error, I tried reinstalling it a few time, but no change... Also recreated the BigSur installation stick. Tried Catalina, this works good for me except for the Wlan(Surface recognized no Wlan, bluetooth works). Anyone can help installing BigSur correctly?

thanks

**Comment by jackjack1-su** [comment]
> Hi again, maybe anyone got a solution for my error, I tried reinstalling it a few time, but no change... Also recreated the BigSur installation stick. Tried Catalina, this works good for me except for the Wlan(Surface recognized no Wlan, bluetooth works). Anyone can help installing BigSur correctly?
> 
> 
> 
> thanks

Then update to BigSur?

**Comment by jackjack1-su** [comment]
> Hi again, maybe anyone got a solution for my error, I tried reinstalling it a few time, but no change... Also recreated the BigSur installation stick. Tried Catalina, this works good for me except for the Wlan(Surface recognized no Wlan, bluetooth works). Anyone can help installing BigSur correctly?
> 
> 
> 
> thanks

No wlan is caused by different version of Airportitlwm.

**Comment by lennykeks** [comment]
ok I tried updating from catalina to BigSur and it went good until there was just less than a minute remaining... Trying it again now...

**Comment by lennykeks** [comment]
UPDATE:

Finally got BigSur installed! You need to install Catalina and then update by simply installing BigSur over Catalina. Install process took around 4 hours... I just had to wait.
