### ISSUE TITLE
brightness problem

### ISSUE THREAD

**Issue by ati46** [badstorm/surface-pro-7-opencore#27]
The brightness is relatively dark after booting, even the maximum brightness is still not enough. After the screen wakes up, the discipline will return to the maximum brightness.

**Comment by badstorm** [comment]
Unfortunately I have never had this problem, so I don't know what it could be caused by. Do the keys to manage the brightness work? Try remove the kext _BrightnessKeys.kext_ and see if something changes.

**Comment by ati46** [comment]
I tried to remove BrightnessKeys.kext to no avail. The phenomenon is like this in the video.
https://github.com/ati46/temp/blob/master/82f1791a7e36dea0390b34b185b6b510.mov

**Comment by ati46** [comment]
After the lid is opened again, the brightness adjustment will return to normal

**Comment by badstorm** [comment]
I close it for inactivity
