### ISSUE TITLE
Stuck at Apple logo when booting BIGSUR

### ISSUE THREAD

**Issue by albcal** [badstorm/surface-pro-7-opencore#28]
hi ! i´m trying to boot BigSur but it stuck on mac logo. thanks for your help

**Comment by albcal** [comment]
Only the mac logo

**Comment by jackjack1-su** [comment]
Setupvirtualmap quirk?
If you have updated your surface firmware, enable it.

**Comment by albcal** [comment]
i'm using opencore configurator and i see the Setupvirtualmap quirk enabled, thanks

**Comment by jackjack1-su** [comment]
Hmmm...
Have you enabled the verbose mode?
I'd like to get some details

**Comment by albcal** [comment]
How do i enable the verbose mode from opencore conf?? I cant find it

**Comment by jackjack1-su** [comment]
> How do i enable the verbose mode from opencore conf?? I cant find it

NVRAM boot-args 
add -v to it

**Comment by albcal** [comment]
![20210618_194001](https://user-images.githubusercontent.com/44923205/122626076-fc6dd080-d06d-11eb-94c8-1c1b23ea77cd.jpg)

**Comment by jackjack1-su** [comment]
> i'm using opencore configurator and i see the Setupvirtualmap quirk enabled, thanks

Alright then try to disable the setupvirtualmap? 
This quirk works differently on different machine

**Comment by jackjack1-su** [comment]
This is my booter quirks
![image](https://user-images.githubusercontent.com/69294205/122626441-3629f000-d0dd-11eb-9645-2f27aa9fc2c8.jpeg)![image](https://user-images.githubusercontent.com/69294205/122626442-3629f000-d0dd-11eb-9772-16ba970f4384.jpeg)

**Comment by albcal** [comment]
same thing with SetupVirtualMap 0
![Captura de Pantalla 2021-06-18 a la(s) 20 18 38](https://user-images.githubusercontent.com/44923205/122627113-31c8ed00-d073-11eb-8c9c-07a6e85d7046.png)

**Comment by jackjack1-su** [comment]
Do you mind trying the efi in this repo with a usb stick?
My computer is updating to macOS 12 at the time so I can't offer useful help.
Sorry.

**Comment by albcal** [comment]
the same with usb stick, no worries, thanks for your help !

**Comment by badstorm** [comment]
Have you tryied all the suggestion described here: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start ?

**Comment by badstorm** [comment]
I close it for inactivity
