### ISSUE TITLE
MacOS Installer not showing

### ISSUE THREAD

**Issue by milesdm** [badstorm/surface-pro-7-opencore#29]
I can't for the life of my figure out what I'm missing here.  I've been unable to get the Installer to show in the boot list on the USB drive.  I've tried catalina / bigsur with a com.apple.recovery.boot folder, and earlier I tried a "full install" based on dmg (created in linux from DMGs i copied from a real mac.)  Nothing seems to show up for me. I've been through the issues list trying everything that looked pertinent, but I'm not sure what I'm missing.  I'm hoping one of you fine folks that understand the OpenCore boot process better can look at my debug log and point me in the right direction.  

Attached is the opencore debug log.

[opencore-2021-06-23-154452.txt](https://github.com/badstorm/surface-pro-7-opencore/files/6704652/opencore-2021-06-23-154452.txt)

**Comment by plsh2me** [comment]
Try selecting config.plist>UEFI>DisableSecurityPilicy. It may work.
<img width="1265" alt="Screenshot 2021-06-27 at 14 14 48" src="https://user-images.githubusercontent.com/24899438/123545855-1d12e600-d752-11eb-8903-1161a20cd3ba.png">

**Comment by badstorm** [comment]
I close it for inactivity

**Comment by milesdm** [comment]
I do have DisableSecurityPolicy enabled.

**Comment by milesdm** [comment]
FYI, I fixed my issue by switching to HFSPlus instead of OpenHFSPlus (which I thought I had tried, however I think I didn't get my config.plist right)
