### ISSUE TITLE
touchpad

### ISSUE THREAD

**Issue by teenza** [badstorm/surface-pro-7-opencore#3]
Catalina work perfect but Big Sur something wrong with single click
Thank you for code.

**Comment by badstorm** [comment]
What kind of problems do you have with the single click? For example, if you click on an icon in the Dock instead of opening the App, does it open a sort of Expose?

In this case you still have "Force Click" active. On the latest Big Sur beta I solved with these commands:

```
defaults write NSGlobalDomain com.apple.trackpad.forceClick -bool false
defaults write com.apple.AppleMultitouchTrackpad ForceSuppressed -bool true
defaults write com.apple.AppleMultitouchTrackpad ActuateDetents -bool false
```

**Comment by teenza** [comment]
Yes thank you I try that
