### ISSUE TITLE
[Question for All] Windows 11 support?

### ISSUE THREAD

**Issue by badstorm** [badstorm/surface-pro-7-opencore#30]
Also on your SP7 you gat this?

![Screenshot 2021-06-29 001127](https://user-images.githubusercontent.com/230256/123710374-ec749e80-d86e-11eb-9737-1c460d4ea21a.png)

**Comment by jackjack1-su** [comment]
It seems a bug on Windows 11
Tech X has a solution by modifying the appraiserres.Dll
I'll upload files later as I don't have my computer at the moment

**Comment by jackjack1-su** [comment]
[appraiserres.dll.zip](https://github.com/badstorm/surface-pro-7-opencore/files/6740767/appraiserres.dll.zip)
When the incompatible window appears, use TaskManager to open the directory of the windows 11, and replace the appraiserres.dll with this one; and then retry upgrading.

**Comment by jackjack1-su** [comment]
Or you can use PE to install it.
Up to you 
:D

**Comment by badstorm** [comment]
I contacted the Surface Support and they decides to replace my device.
