### ISSUE TITLE
Kext for Realtek USB 3.0 card reader

### ISSUE THREAD

**Issue by plsh2me** [badstorm/surface-pro-7-opencore#34]
I own a surface pro 7 8gb/128gb version 1866. It have the Realtek usb 3.0 card reader. 
![sdcard](https://user-images.githubusercontent.com/24899438/124382474-8d27eb80-dcbf-11eb-8879-f6ce09119118.jpg)

Please guys help me to find out the working kext for the card reader. 
I already tried several kexts, but no luck.
<img width="337" alt="Screenshot 2021-07-04 at 12 04 45" src="https://user-images.githubusercontent.com/24899438/124382573-163f2280-dcc0-11eb-9f63-88f63a583fa4.png">

If anyone have the kext please share me.

**Comment by badstorm** [comment]
Please try the solution provided by @jackjack1-su here https://github.com/badstorm/surface-pro-7-opencore/pull/33
If works, please close the issue.

**Comment by plsh2me** [comment]
Thats great, it works. 
<img width="1037" alt="Screenshot 2021-07-05 at 10 11 08" src="https://user-images.githubusercontent.com/24899438/124448667-9aee7700-dd7a-11eb-821f-3455687da858.png">

Thank you very much
