### ISSUE TITLE
"NO NAME (dmg)" Is the Only Option In Opencore USB First Boot

### ISSUE THREAD

**Issue by LooP403** [badstorm/surface-pro-7-opencore#38]
Hello, so when I boot into the USB I make with this, the only option from it is "NO NAME (dmg)" (although sometimes when I tried to make a new drive it didn't have the "(dmg)" part. Has anyone else come across this error? I feel like I'm missing a crucial step for this, but I went through every opencore guide I could yet came across nothing like this.

One of the main things I tried doing was putting it directly on the ssd, but the result was the same.
Any help is appreciated :)

**Comment by badstorm** [comment]
It looks like you created the USB installer incorrectly.  Try following this guide:

https://dortania.github.io/OpenCore-Install-Guide/installer-guide/

**Comment by LooP403** [comment]
Hey, so I went and recreated the drive, but im still getting this issue. ive tried many fixes that were reccomended in other issues people made but nothing seems to fix the issue. 
When i select the no name option it just boots back into the selection screen. So far the only progress i made was having a fancier gui when i installed and enabled HfsPlus.efi

Anything i can try?
