### ISSUE TITLE
Does messages works?

### ISSUE THREAD

**Issue by hackintosher121** [badstorm/surface-pro-7-opencore#4]
So I am trying to sign in to messages with my Apple ID, but then it just shows there is an unknown error occurred, I am just wondering is it just me or everyone else using this efi folder have the same issue

**Comment by hackintosher121** [comment]
Thanks ahead btw

**Comment by badstorm** [comment]
I'll try right now but i can send message without any problems. Also Facetime works.
Try to change Serial Number on `config.plist`

**Comment by hackintosher121** [comment]
I did change the serial number on config.plist, but every time I try to sign in it just says an error occurred. FaceTime doesn't work either, it just simply says "an error occurred during authentication."

**Comment by badstorm** [comment]
Have you tried this: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#generate-a-new-serial

**Comment by hackintosher121** [comment]
Yeah I did

**Comment by badstorm** [comment]
Try this: download [Opencore Configurator](https://mackie100projects.altervista.org/download-opencore-configurator) and open the `config.plist`.
Then in _PlatformInfo_ section click on the dropdown near _Check Coverage_ and select `MacBookPro16,2` and the save the file.

**Comment by hackintosher121** [comment]
I just tried FaceTime but it still says "an error occurred during authentication", I am still waiting for messages now through.

**Comment by hackintosher121** [comment]
It says "An error occurred" as well for messages.

**Comment by hackintosher121** [comment]
And now it says an "An unknown error occurred" for signing in Apple ID as well

**Comment by badstorm** [comment]
Have you tried login with your Apple ID on a real mac?

**Comment by badstorm** [comment]
Try this: https://osxdaily.com/2016/10/23/fix-icloud-unknown-error-cant-connect-problem-mac/

**Comment by hackintosher121** [comment]
NGL I have an iPhone but I don't have a Mac, I bought this SP7 for school, and I wanna try out macOS, that's the reason I got Hackintosh on it.

**Comment by hackintosher121** [comment]
BTW I can sign back in to iCloud now but still no luck for messages and FaceTime.

**Comment by badstorm** [comment]
I don't think is a problem related to the hack. Try a clean installation again and if u steel have the problem try create a new apple id only for test to be sure.

**Comment by hackintosher121** [comment]
Which version of mac r u using right now? Because I've tried reinstalling it multiply times and created and Apple ID just for the sake of it but still no luck.

**Comment by badstorm** [comment]
![macos_version](https://user-images.githubusercontent.com/230256/99898651-63c3cd80-2ca3-11eb-8dcd-8a42a79bc5d0.png)

I honestly don't know how to help you with your problem. It would be helpful to know if others have the same problem with this OC configuration as you.

**Comment by hackintosher121** [comment]
I've fixed it now, it was the problem with the WiFi, it works with a VPN, thanks for the help :)
