### ISSUE TITLE
macOS don't detect TypeCore Mouse/Keyboard

### ISSUE THREAD

**Issue by Darkdestroyer636** [badstorm/surface-pro-7-opencore#40]
When booting the Mac OS installer it boots to a screen telling me to turn on my keyboard and mouse.

Surface type cover is connected

**Comment by badstorm** [comment]
Which Release did you used? Have already you tried and old one?

**Comment by Darkdestroyer636** [comment]
I used the latest 1773 release
no I have not tried an older release
I will do that now

**Comment by Darkdestroyer636** [comment]
This did not help, I managed to install macOS Big Sur by using usb-C to connect a keyboard and mouse but I have an issue, I cannot use trackpad gestures, such as 2 finger scroll

**Comment by badstorm** [comment]
I ran into the same problem. I think is an incorrect USB mapping. Get the release 1775 and try (from mac or win) to generate your  `UTBMap.kext` with [USBToolBox](https://github.com/USBToolBox/tool) and replace it in `OC/Kexts` folder. Let me know if it work.

**Comment by Darkdestroyer636** [comment]
this didn't seem to solve the issue, trackpad gestures still aren't working and I get the bluetooth popup to pair my mouse every boot up. I have made a UTBMap.kext with USBToolBox and still not working? what else can I try

**Comment by Darkdestroyer636** [comment]
![Screenshot 2021-11-08 at 10 56 42](https://user-images.githubusercontent.com/86473412/140730113-f12502d9-9752-4424-ac7e-59815346dd75.png)
image of issue. as you can see it still isn't working. UBTMap.kext is enabled.
this is my efi
https://drive.google.com/file/d/1EolQcp5mW-SSJGy6y1gzN2gr16RQjafz/view?usp=sharing

**Comment by Darkdestroyer636** [comment]
can you try fix it?

**Comment by Zaphkeil** [comment]
same problem too,but when i connent to my logit G502 the type cover and trackpad can work

**Comment by Darkdestroyer636** [comment]
I don't know what I can do to fix it to be honest, my main hack is a Dell Inspiron 5577 which is working fine with trackpad gestures and all, only hiccup I had was when upgrading from OpenCore 0.6.5 to 0.7.5 usb was a pain to get working, remapping with hackintool to create some ssdts fixed it. If I find time I will try use hackintool to remap usb and report back if it works!

**Comment by Darkdestroyer636** [comment]
Update: it didn't

**Comment by Helloyunho** [comment]
Somehow I fixed this issue with two step:
1. Remap the USB
2. Remove VoodooI2C and use https://github.com/Xiashangning/BigSurface

**Comment by badstorm** [comment]
Thanks @Helloyunho, added it to last commit. In any case also if the TypeCover works, macOS Installer show the fullscreen alert to connect a keyboard/mouse so we need to connect in any way an usb keyboard. Did you found a fix also for this?

**Comment by Helloyunho** [comment]
@badstorm At least in the recovery mode, it doesn't show anything related to missing keyboard/mouse. And both of them works just fine.
I'll still try booting into the macos installer.

**Comment by liuson945** [comment]
我surface pro4 也有同样问题，oc 0.7.6 u盘全新安装bigsur11-bigsur11.6都没有问题，但是全新u盘安装Monterey12.0.1也是出现需要打开鼠标和键盘的提示，无法进入恢复模式！我尝试bigsur11.6 OTA升到12.0.1可以完美升级，但是就不能u盘安装！
![2021-11-14 152353](https://user-images.githubusercontent.com/76866901/141677582-2f351577-58e3-4352-8ff1-db01a70c8a39.jpg)

**Comment by Helloyunho** [comment]
Tried using a Big Sur installer and it works as intended.

**Comment by Darkdestroyer636** [comment]
ok just used the latest commit and made a UTBMap.kext, I don't seem to be having much luck with getting gestures and stuff to work

**Comment by Darkdestroyer636** [comment]
the good news is it seemingly is no longer showing the connect keyboard and mouse screen, I will try using the mouse commands that you mentioned in the readme, wish me luck

**Comment by Helloyunho** [comment]
> ok just used the latest commit and made a UTBMap.kext, I don't seem to be having much luck with getting gestures and stuff to work

Hmm, that's weird because even the gesture works perfectly for me

**Comment by Darkdestroyer636** [comment]
Ok narrowed it down to my surface not booting from my usb

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Darkdestroyer636** [comment]
I am on Monterey so could that mean anything

**Comment by Helloyunho** [comment]
Maybe, but I think I heard BigSurface also supports Monterey...

**Comment by Darkdestroyer636** [comment]
wait send me your OpenCore folder, if its just my usb map being weird maybe using your efi will wield different results

**Comment by Darkdestroyer636** [comment]
also forgot to mention I mapped usb using windows, could that be it

**Comment by Helloyunho** [comment]
> also forgot to mention I mapped usb using windows, could that be it

no because I also mapped it on windows



> wait send me your OpenCore folder, if its just my usb map being weird maybe using your efi will wield different results

my surface pro is using i7 so you might need to edit something

**Comment by Darkdestroyer636** [comment]
my surface is also i7 :p

**Comment by Darkdestroyer636** [comment]
ok I tried mapping through Mac OS, ill send over my efi for you to have a look at along with my utbmap.kext, in the meantime send over yours

here they are


https://drive.google.com/drive/folders/1Ehv2EySWePIx9AbXULKK2d1sNmjeca7t?usp=sharing efi
utbmap should be in it

**Comment by Darkdestroyer636** [comment]
is anyone still there

**Comment by Helloyunho** [comment]
yeah, just my another hackintosh kernel panics so many times and got delayed

**Comment by Helloyunho** [comment]
anyway, here's mine: [OC.zip](https://drive.google.com/file/d/1gqlUcTnnMpulXLI5OKU9LoTSBRQ7Nnpj/view?usp=sharing)

**Comment by Darkdestroyer636** [comment]
Oh lol, I have sent my efi above. Possible you can send yours for me to try

**Comment by Darkdestroyer636** [comment]
Oh just saw your above message :p

**Comment by Darkdestroyer636** [comment]
ok testing it now

**Comment by liuson945** [comment]
> 尝试使用Big Sur安装程序，它工作正常。

你说的是big surface吗？我试试，谢谢

**Comment by Darkdestroyer636** [comment]
> > 尝试使用Big Sur安装程序，它工作正常。
> 
> 你说的是big surface吗？我试试，谢谢


big surface is a kext which aims to integrate surface drivers into 1 unified kext, so far volume buttons and the type cover are the only working ones

**Comment by liuson945** [comment]
> > > 尝试使用Big Sur安装程序，它工作正常。
> > 
> > 
> > 你说的是big surface吗？我试试，谢谢
> 
> big surface is a kext which aims to integrate surface drivers into 1 unified kext, so far volume buttons and the type cover are the only working ones

好的，多谢！我想知道它在Monterey12.0.1上触摸板实现了多手势吗？

**Comment by Darkdestroyer636** [comment]
> > > > 尝试使用Big Sur安装程序，它工作正常。
> > > 
> > > 
> > > 你说的是big surface吗？我试试，谢谢
> > 
> > 
> > big surface is a kext which aims to integrate surface drivers into 1 unified kext, so far volume buttons and the type cover are the only working ones
> 
> 好的，多谢！我想知道它在Monterey12.0.1上触摸板实现了多手势吗？

ok I have not been able to get multitouch gestures to work in Monterey with big surface, albeit I haven't been able to check if it works with big Sur either

**Comment by Darkdestroyer636** [comment]
ok my last idea for Monterey is Hackintool usb dsdts and bigsurface

**Comment by Darkdestroyer636** [comment]
Ok that failed, big sur is my next test

**Comment by Darkdestroyer636** [comment]
Big sur fixes gestures and stuff as far as I can tell in setup

**Comment by Darkdestroyer636** [comment]
So just stay on big sur until sun mapping seemingly gets fixed on Monterey

**Comment by Darkdestroyer636** [comment]
USB not sun :p

**Comment by Xiashangning** [comment]
@Darkdestroyer636 well, if you look into BigSurface's closed issues, you will find that some weird IOProbeScore priority thing caused the typeover unusable in Monterey, changing its IOProbeScore to 9999 fixed this problem, I will include this update in next release

**Comment by Darkdestroyer636** [comment]
thank you

**Comment by Helloyunho** [comment]
seems like it's time to add BigSurface to readme.md

**Comment by Darkdestroyer636** [comment]
will trackpad system preferences ever be fixed?

**Comment by liuson945** [comment]
> will trackpad system preferences ever be fixed?

将：</array>
			<key>IOClass</key>
			<string>SurfaceTypeCoverDriver</string>
			<key>IOProbeScore</key>
			<integer>9999</integer>
			<key>IOProviderClass</key>
			<string>IOHIDInterface</string>
			<key>ProcessBluetoothMouseStopsTrackpad</key>
			<false/>
			<key>ProcessUSBMouseStopsTrackpad</key>
			<false/>
			<key>QuietTimeAfterTyping</key>
			<integer>200</integer>
			<key>RM,deliverNotifications</key>
			<true/>
<key>IOProbeScore</key>
<integer>300</integer>修改为：9999 解决！

**Comment by Darkdestroyer636** [comment]
I just discovered one more issue, not sure if it can be fixed and if it is only my device but If I start the surface up with a usb c adapter to hook up my second display it doesn't work. if I boot with it unplugged and plug it in after boot it does

**Comment by badstorm** [comment]
https://github.com/badstorm/surface-pro-7-opencore/releases/tag/1776
