### ISSUE TITLE
OpenCore Boot menu only showing Windows partition

### ISSUE THREAD

**Issue by thaiiy** [badstorm/surface-pro-7-opencore#41]
Hi there,
I have a Surface Book 3 with i5 10th Gen CPU too.
After copying your EFI over, my USB drive containing my MacOS boots to the Opencore Boot Menu with only MS Windows as the partition available.

Did you have to change your BIOS settings to anything? I can't see many settings within the Surface BIOS, no AHCI settings to change.
Thanks

**Comment by badstorm** [comment]
This repo is specific only for Surface Pro. I don't have your device to make tests. I move this issue to discussions. Maybe some other users can help you.
