### ISSUE TITLE
No Macos installer partition at opencore boot menu

### ISSUE THREAD

**Issue by L4cT4r** [badstorm/surface-pro-7-opencore#43]
Hi guys, i'm trying to install macos Big Sur on my surface pro 7, but it the installer partition doesn't show in the opencore boot menu. 
My device details are:
-SAM CONTROLLER :                   14.418.139
-TOUCH FIRMWARE :                   3.1.65.139
-PD CONTROLLER :                      3.6.1
-NUVOTON dTPM :                      7.2.2..0
-Intel Management Engine :        13.01763.7
-System UEFI :                              9.107.140

I already tried the solutions from the official github of opencore 
- Can't see macOS partitions
Main things to check:

ScanPolicy set to 0 to show all drives
Have the proper firmware drivers such as HfsPlus(Note ApfsDriverLoader shouldn't be used in 0.5.8)
Set UnblockFsConnect to True in config.plist -> UEFI -> Quirks. Needed for some HP systems
Set SATA Mode: AHCI in BIOS
Set UEFI -> APFS to see APFS based drives:
EnableJumpstart: YES
HideVerbose: NO
If running older versions of High Sierra(ie. 10.13.5 or older), set the following:
MinDate: -1
MinVersion: -1

But no difference, need some help thanks in advance

**Comment by Darkdestroyer636** [comment]
I had this issue too, switching from openhfsplus.efi to hfsplus.efi fixed it. try this too, if you have any more issues tell me, currently my issue is i cant use multi touch gestures with the trackpad and i have to disconnect and reconnect the keyboard to even use it. if you have this issue too, tell me, i will try to find a solution

**Comment by L4cT4r** [comment]
> I had this issue too, switching from openhfsplus.efi to hfsplus.efi fixed it. try this too, if you have any more issues tell me, currently my issue is i cant use multi touch gestures with the trackpad and i have to disconnect and reconnect the keyboard to even use it. if you have this issue too, tell me, i will try to find a solution

Thank you @Darkdestroyer636  for your reply, sadly this didnt fix the problem, just to be sure I need to replace the file and change my config.plist in uefi -> drivers !?

**Comment by plsh2me** [comment]
@L4cT4r Hi, Go to UEFI>DisableSecurityPolicy select it.
Hope it will work
![Screenshot 2021-10-05 at 21 49 49](https://user-images.githubusercontent.com/24899438/136100563-b1961489-1215-4b35-bec1-2583baa51eda.png)
.

**Comment by L4cT4r** [comment]
> @L4cT4r Hi, Go to UEFI>DisableSecurityPolicy select it. Hope it will work ![Screenshot 2021-10-05 at 21 49 49](https://user-images.githubusercontent.com/24899438/136100563-b1961489-1215-4b35-bec1-2583baa51eda.png) .

@plsh2me that fixed it, thank you so much I apreciate it.
