### ISSUE TITLE
Update BigSurface as now Battery is supported on SP7

### ISSUE THREAD

**Issue by Xiashangning** [badstorm/surface-pro-7-opencore#47]

**Comment by badstorm** [comment]
https://github.com/badstorm/surface-pro-7-opencore/releases/tag/1776

**Comment by badstorm** [comment]
With the version 4.0 of BigSurface  macos 12.1 install works but when macos start for the first time (before install assistant) I get kernel panic (Userspacewatchdog timeout). Any ideas?

**Comment by Xiashangning** [comment]
...Emmm, I have no idea, is it working after the first time?

**Comment by badstorm** [comment]
No is stuck on KP

**Comment by Xiashangning** [comment]
Can I see the kp log? Other people have not experienced such kp so far (SP7)

**Comment by badstorm** [comment]
make a test with last release 1776
Have you find why installer always akk for keyboard/mouse also if typecover works?

**Comment by Xiashangning** [comment]
That means BigSurface failed to load

**Comment by Xiashangning** [comment]
Enable Misc-Debug-`Disable Watchdog` and there won't be any problem any more.
PS: I have enabled that option for a long time so I am not aware that my kext would actually cause a watchdog kp. Maybe I have to figure out it as it is evidently a bug...

**Comment by badstorm** [comment]
With `Disable Watchdog` enabled same problem
