### ISSUE TITLE
BigSurface issues with the new release (BigSurface 4.0, Release 1776 of badstorm opencore)

### ISSUE THREAD

**Issue by Darkdestroyer636** [badstorm/surface-pro-7-opencore#49]
Welp, with new release comes new keyboard problems, bigsurface 4.0 seems to not have battery nor keyboard+trackpad working in my experience under Monterey 12.1, testing big Sur when downloaded

**Comment by badstorm** [comment]
On my SP7 with Monteray 12.1 typecover (keyboard/mouse) works, but in the installer i need to attach a usb mouse or keyboard to hide the fullscreen missing keyboard/mouse alert. Try to buil a custom USB kext using the usb windows tool.

**Comment by Darkdestroyer636** [comment]
i have tried this, my issue seems to lie in bigsurface as if i use 3.0 it works

**Comment by Darkdestroyer636** [comment]
ok i attempted a big sur downgrade and it did not help. something about 4.0 does not like my system, hope for an update soon. definitely want functional battery

**Comment by Darkdestroyer636** [comment]
> On my SP7 with Monteray 12.1 typecover (keyboard/mouse) works, but in the installer i need to attach a usb mouse or keyboard to hide the fullscreen missing keyboard/mouse alert. Try to buil a custom USB kext using the usb windows tool.

so as i have said 3 days ago i still am having issues, my best bet is gonna be downloading the old version of your repo and trying to upgrade to bigsurface 4.0

if this works i will let you know

**Comment by Darkdestroyer636** [comment]
It did not work. Anyone had any luck?

**Comment by Darkdestroyer636** [comment]
trying release 1777 now

**Comment by Darkdestroyer636** [comment]
and it fixed it!

**Comment by Darkdestroyer636** [comment]
now on a sidenote this was on big sur so theres the good news. now attempting a monterey upgrade...

**Comment by Darkdestroyer636** [comment]
actually nevermind. i will just stick to big sur for it being more stable, its what i run on my actual mac. eventually i will install macOS to an sd card to test monterey or something

**Comment by Darkdestroyer636** [comment]
actually nevermind. i will just stick to big sur for it being more stable, its what i run on my actual mac. eventually i will install macOS to an sd card to test monterey or something
