### ISSUE TITLE
Graphical Glitches

### ISSUE THREAD

**Issue by joeyboey** [badstorm/surface-pro-7-opencore#5]
The Hardware is properly recognised but the screen glitches, mostly when something happens on screen, i.e. moving the cursor or windows. I did research this issue but did not find anything useful.
I also tried to make my own config from scratch. While I did also work just fine, I wasn't able to fix the screen glitching.

**Comment by hackintosher121** [comment]
Just simply change the resolution, this happens to everyone

**Comment by joeyboey** [comment]
Okay, if I switch to Default it works. But the interface is pretty huge. So no way to use the smallest scaling?

**Comment by badstorm** [comment]
Currently I have not found other solutions. It appears that the problem is related to the Ice Lake processors. Let's see if the problem is solved in the next versions of WhateverGreen.

For now, you can only search for the non-retina resolution that suits you best.

**Comment by Ehco1996** [comment]
> Just simply change the resolution, this happens to everyone

@hackintosher121  @badstorm 

what’s resolution you guys use ? i can only use 800x600
