### ISSUE TITLE
Wifi in the Installer

### ISSUE THREAD

**Issue by mashiro494** [badstorm/surface-pro-7-opencore#51]
Hello, I am currently having some issue with the install progress, where I'm able to boot to the installer, however when I'm trying to install Big Sur, it just says that you need an internet connection to do so, but I'm could not find the WiFi icon anywhere so is there anyway that I can install it? I was using the opencore install guide to create the boot USB. 

Surface Spec: 
i5
8GB
256GB

any help would be appreciated

**Comment by badstorm** [comment]
The last release is for Monteray. If you need support for Big Sur you must update the `AirportItlwm.kext` with the [BigSur version form](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.1.0/AirportItlwm_v2.1.0_stable_BigSur.kext.zip) or use `itlwm.kext` with Eliport.
