### ISSUE TITLE
No macOS Is Working I tried everything

### ISSUE THREAD

**Issue by landondoestech** [badstorm/surface-pro-7-opencore#69]
About 1 week ago i wanted to install macOS using a SD Card.I downloaded your EFI and used it to install macOS Monterey (You said ventura wasent supported yet) but when in installation it would crash No macOS Intsall was found So i tried using a virtual machine and connected my SD Card but then when i boot it off it it just goes to a black screen Now I just updated to your Ventura Supported EFI and when that happend There was Nothing other than Windows I looked at the config.plist i pressed spacebar nothing will work so i have a few questions

Can i install macOS Ventura on a SD Card
Why is there no macOS Options in your EFI(Because my SD Card still has that copy of montery and it wont show now)

**Comment by landondoestech** [comment]
Ok a few updates The macOS Installer That i used had the apple Partition map which i think isnt bootable and i think that the macos installation i had was corupted on my sd card or it has the apple partition map so i will update this when i can make a ventura installer using my 2011 mac and see if i can install

**Comment by landondoestech** [comment]
also i made my own efi with the same kext and drivers

**Comment by MaksimDeve** [comment]
SD card very slow to use for OS, i'm try Windows 10(11), Ubuntu on SP7 SD card  i's very bad :(

**Comment by 368406148** [comment]
It‘s difficult to use a very old mac to create the ventura installer.

**Comment by landondoestech** [comment]
Ok so i got it working it was the SD Cards fault and i used the Orignal EFI.So do not use a SD Card It does not work.
