### ISSUE TITLE
Stuck at whatevergreen during install

### ISSUE THREAD

**Issue by techtwist-creator** [badstorm/surface-pro-7-opencore#7]
Hello i tried installing using your efi but get stuck at whatevergreen .......
here is a picture of the verbose
![image0](https://user-images.githubusercontent.com/72697051/103523819-7c2e2700-4ea2-11eb-9770-c3f63f1d931b.jpg)
if you could help me please

**Comment by badstorm** [comment]
Did you use the Release version? If so, try update the config file from [master](https://github.com/badstorm/surface-pro-7-opencore/blob/master/EFI/OC/config.plist) and let me know if work.

**Comment by badstorm** [comment]
@techtwist-creator Since there are no more updates, I close this problem. You can always reopen it if you need it.
