### ISSUE TITLE
Installer stuck at "less than a minute remaining"

### ISSUE THREAD

**Issue by fernandomema** [badstorm/surface-pro-7-opencore#71]
I'm trying to install Monterrey. Everything's seems to work fine. But when the installer ends, after reboot, new entry appears on the open ore named "Mac installer". It shows the Mac logo and text saying "about 29 mins left". Then everything goes well until "less than a minute remaining". I waited like 5 hours, but nothing. It freezes at less than a minute.
Dou you have any idea?
I'm on the i7 version of the surface, I don't know if it can be the problem.
Thanks in advice.

**Comment by 368406148** [comment]
I waited for 12 hours. So please just wait over there. lolSent from my iPhoneOn Aug 2, 2022, at 21:38, Fernando Merino ***@***.***> wrote:﻿
I'm trying to install Monterrey. Everything's seems to work fine. But when the installer ends, after reboot, new entry appears on the open ore named "Mac installer". It shows the Mac logo and text saying "about 29 mins left". Then everything goes well until "less than a minute remaining". I waited like 5 hours, but nothing. It freezes at less than a minute.
Dou you have any idea?
I'm on the i7 version of the surface, I don't know if it can be the problem.
Thanks in advice.

**Comment by fernandomema** [comment]
You're right, it worked perfectly after waiting 7 hours.
Thanks you.
