### ISSUE TITLE
Do Ambient Light Sensor Work？

### ISSUE THREAD

**Issue by wxxsfxyzm** [badstorm/surface-pro-7-opencore#72]
Newly installed Monterey on my SP7, but find no Auto Adjust Brightness in Display Settings, I don't know whether it is a bug.
![图像](https://user-images.githubusercontent.com/65166044/185748790-2470a72f-5551-42ea-b12a-dc981b18b184.jpeg)

**Comment by badstorm** [comment]
I think is now supported with the last [BigSurface Kext](https://github.com/Xiashangning/BigSurface/releases/tag/v6.2). I'll update it in the next release.
