### ISSUE TITLE
 AppleALC Loud noise on the speaker after waking up from sleep.Audio problem makes device sleep unnormal get hot.disable audio.kext  device get normal

### ISSUE THREAD

**Issue by Rainringgoaway** [badstorm/surface-pro-7-opencore#75]

**Comment by badstorm** [comment]
Since there is no custom configuration for AppleALC in this config, I suggest you to open this question directly to [AppleALC repo]( https://github.com/acidanthera/bugtracker). You can share the link here so some other users can read the evolution of the quesiton.

**Comment by gsmji** [comment]
yes, when it get sleep.the battery keeps falling down!
