### ISSUE TITLE
the speed of the type-C is slow,only 480mbps

### ISSUE THREAD

**Issue by yejunjie10311031** [badstorm/surface-pro-7-opencore#79]
![PXL_20221002_032346640](https://user-images.githubusercontent.com/62139629/193436501-bcc6d30e-b683-4794-8424-5d4dbd713870.jpg)
![PXL_20221001_143022982 MP](https://user-images.githubusercontent.com/62139629/193436509-967ad423-821e-4140-9a6b-e43c402e8137.jpg)

**Comment by badstorm** [comment]
In the last relase (1884) I replace the old `USBPorts` kext with the new [USBMap](https://github.com/corpnewt/USBMap)

**Comment by wangjiangb** [comment]
I still find the USB-C connection slow in the latest release. The USB-C connection can only uses HS02 instead of SS02. 

@badstorm
