### ISSUE TITLE
USBMap complet!!!

### ISSUE THREAD

**Issue by Rainringgoaway** [badstorm/surface-pro-7-opencore#86]
1.add Express card
2.change port type
3.delete unnecessary port
[USBMap.kext.zip](https://github.com/badstorm/surface-pro-7-opencore/files/9881199/USBMap.kext.zip)
Maybe need to change model name as ur device use like this
<img width="848" alt="2022-10-27 23 49 03" src="https://user-images.githubusercontent.com/88170324/198343216-86b66f42-8245-49f0-8380-e4232f203e77.png">

**Comment by badstorm** [comment]
Make a new PR with your edits so I can integrate it in the next release. :)
