### ISSUE TITLE
macOS doesn't boot after EFI update

### ISSUE THREAD

**Issue by milankkk** [badstorm/surface-pro-7-opencore#96]
Just now i updated my efi with the new release, but now when i boot my macOS Monterey drive it just restarts at the end of the boot.

I also turned on "-v keepsyms=1 debug=0x100" in hopes of seeing if there was a problem, but i didn't see any.

**Comment by badstorm** [comment]
Wich release you used? The last is for Ventura. Check the wifi driver: try use `itlwm.kext` instead of `AirportItlwm.kext`

**Comment by badstorm** [comment]
Closed for inactivity
